# Generated by Django 5.1 on 2025-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('entrenador', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('color_uniforme', models.CharField(max_length=50)),
            ],
        ),
    ]
